FROM jpr/ubuntu

LABEL autor="JPR"

# Instalar Nginx
RUN apt-get update && apt-get install -y nginx && apt-get clean

# Copiar la configuración personalizada de Nginx
COPY ./nginx.conf /etc/nginx/nginx.conf

# Configurar permisos para Nginx
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

# Exponer el puerto 80
EXPOSE 80

# Ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]